version: '2'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./:/code
      - ./docker/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - ticket-network
  php:
    build:
      context: ./docker/php
    volumes:
      - ./:/code
    networks:
      - ticket-network
  mongo:
    image: mongo:3.4
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/datadir:/data/db
    networks:
      - ticket-network

networks:
  ticket-network:
    driver: bridge
